DROP DATABASE IF EXISTS employeeTrackerDB;
CREATE DATABASE employeeTrackerDB;
USE employeeTrackerDB;

CREATE TABLE department (
  id INTEGER(3) NOT NULL AUTO_INCREMENT, 
  name VARCHAR(30) NOT NULL,
  PRIMARY KEY (id)
);  

CREATE TABLE role (
  id INTEGER(3) NOT NULL AUTO_INCREMENT,
  title VARCHAR(30) NOT NULL,
  salary DECIMAL(10,2) NOT NULL,
  department_id INTEGER(3) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE employee (
  id INTEGER(3) NOT NULL AUTO_INCREMENT,
  first_name VARCHAR(30) NOT NULL,
  last_name VARCHAR(30) NOT NULL,
  role_id INTEGER(3) NOT NULL,
  manager_id INTEGER(3), 
  PRIMARY KEY (id)
);  